name: Build BmpToPng

# Permite ejecutar manualmente desde la interfaz de GitHub
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup MSVC Build Tools
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: latest

      - name: Compile BmpToPng
        shell: cmd
        run: |
          cl /EHsc /Fe:BmpToPng.exe *.c

      - name: Upload compiled binary
        uses: actions/upload-artifact@v4
        with:
          name: BmpToPng-exe
          path: BmpToPng.exe
