name: Build BmpToPng

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true

      - name: Install build tools
        run: |
          pacman -S --noconfirm make mingw-w64-x86_64-gcc

      - name: Build BmpToPng
        run: |
          make

      - name: Upload compiled binary
        uses: actions/upload-artifact@v4
        with:
          name: BmpToPng-exe
          path: BmpToPng.exe
