name: Build BmpToPng

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install MinGW
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: mingw-w64-x86_64-gcc make

      - name: Build binaries using Makefile
        shell: bash
        run: |
          make

      - name: Upload compiled binaries
        uses: actions/upload-artifact@v4
        with:
          name: BmpToPng-binaries
          path: |
            bmp2png.exe
            png2bmp.exe
