name: Build BmpToPng

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true

      - name: Install build tools
        run: |
          pacman -S --noconfirm make mingw-w64-x86_64-gcc

      - name: Build BmpToPng
        shell: bash
        run: |
          make

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: BmpToPng-exe
          path: BmpToPng.exe
